// Shader written by Enchanted_Games (https://enchanted.games)
// Please don't steal this code and use it without asking me first
// Any functions not made by me will include a credit line at the top of them

// Generated by https://outlines.enchanted.games
//Thank you for drawing outline texture!!! by taichan_

const vec4 block_COLOURS[] = vec4[](
	vec4(0, 0.749, 1, 0.3),
	vec4(0, 0.3333, 1, 0.3)
);
#define block_ANIM_SPEED 1000
#define block_COLOUR_PERIOD 0.5
#define block_SMOOTH_MIX false
#define block_ANIMATE_WITH_DISTANCE true
#define block_ANIMATE_ALONG_LINES true
#define block_ANIM_DIRECTION 1
#define block_LINE_THICKNESS 2.5

const vec4 hitbox_COLOURS[] = vec4[](
	vec4(0.5794, 1, 0.6425, 1),
	vec4(1, 1, 1, 1)
	);
#define hitbox_ANIM_SPEED 500
#define hitbox_COLOUR_PERIOD 1
#define hitbox_SMOOTH_MIX true
#define hitbox_ANIMATE_WITH_DISTANCE false
#define hitbox_ANIMATE_ALONG_LINES true
#define hitbox_ANIM_DIRECTION 1
#define hitbox_LINE_THICKNESS 2
#define hitbox_APPLY_TO_ALL_LINES true