
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.ranahiromod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.ranahiromod.item.ZoniItem;
import net.mcreator.ranahiromod.item.YotoItem;
import net.mcreator.ranahiromod.item.YakisobaItem;
import net.mcreator.ranahiromod.item.WoodenShortSwordItem;
import net.mcreator.ranahiromod.item.WindrItem;
import net.mcreator.ranahiromod.item.WindhiroItemItem;
import net.mcreator.ranahiromod.item.WindMagicItem;
import net.mcreator.ranahiromod.item.WindMagic2Item;
import net.mcreator.ranahiromod.item.WetNoriItem;
import net.mcreator.ranahiromod.item.WeaponhiroItemItem;
import net.mcreator.ranahiromod.item.WawawawawawawawawawawawawawawawawawawawawawawawawawawawawawaItem;
import net.mcreator.ranahiromod.item.WaterhiroItemItem;
import net.mcreator.ranahiromod.item.WaterItem;
import net.mcreator.ranahiromod.item.WarderItem;
import net.mcreator.ranahiromod.item.WardenhiroItemItem;
import net.mcreator.ranahiromod.item.VoltrItem;
import net.mcreator.ranahiromod.item.VolthiroItemItem;
import net.mcreator.ranahiromod.item.VazafilaSwordItem;
import net.mcreator.ranahiromod.item.VazafilaPowerItem;
import net.mcreator.ranahiromod.item.VazafilaKatanaItem;
import net.mcreator.ranahiromod.item.UndefinedRamenItem;
import net.mcreator.ranahiromod.item.UndefinedMeatItem;
import net.mcreator.ranahiromod.item.UndefinedGunItem;
import net.mcreator.ranahiromod.item.TreasureChestItemItem;
import net.mcreator.ranahiromod.item.Topaz_toolSwordItem;
import net.mcreator.ranahiromod.item.Topaz_toolShovelItem;
import net.mcreator.ranahiromod.item.Topaz_toolPickaxeItem;
import net.mcreator.ranahiromod.item.Topaz_toolHoeItem;
import net.mcreator.ranahiromod.item.Topaz_toolAxeItem;
import net.mcreator.ranahiromod.item.Topaz_toolArmorItem;
import net.mcreator.ranahiromod.item.TopazItem;
import net.mcreator.ranahiromod.item.ThisIsYourMealItem;
import net.mcreator.ranahiromod.item.TaichanBowItem;
import net.mcreator.ranahiromod.item.SwordOfBosshiroItem;
import net.mcreator.ranahiromod.item.SweepItemItem;
import net.mcreator.ranahiromod.item.SunRodItem;
import net.mcreator.ranahiromod.item.SumahiroPhoneItem;
import net.mcreator.ranahiromod.item.StrangeInkItem;
import net.mcreator.ranahiromod.item.StoneShortSwordItem;
import net.mcreator.ranahiromod.item.SpladotRodItem;
import net.mcreator.ranahiromod.item.SpladotPowerItem;
import net.mcreator.ranahiromod.item.SpawnerBreakerItem;
import net.mcreator.ranahiromod.item.SoulIngotItem;
import net.mcreator.ranahiromod.item.SoulGriefSwordItem;
import net.mcreator.ranahiromod.item.SoulGriefIngotItem;
import net.mcreator.ranahiromod.item.SmasherItem;
import net.mcreator.ranahiromod.item.SealedMysteriouDocumentItem;
import net.mcreator.ranahiromod.item.SapphireToolSwordItem;
import net.mcreator.ranahiromod.item.SapphireToolShovelItem;
import net.mcreator.ranahiromod.item.SapphireToolPickaxeItem;
import net.mcreator.ranahiromod.item.SapphireToolHoeItem;
import net.mcreator.ranahiromod.item.SapphireToolAxeItem;
import net.mcreator.ranahiromod.item.SapphireItem;
import net.mcreator.ranahiromod.item.SapphireArmorArmorItem;
import net.mcreator.ranahiromod.item.SakuramochiItem;
import net.mcreator.ranahiromod.item.SKLiner5077PowerItem;
import net.mcreator.ranahiromod.item.SKLiner5077BladeItem;
import net.mcreator.ranahiromod.item.RubyToolSwordItem;
import net.mcreator.ranahiromod.item.RubyToolShovelItem;
import net.mcreator.ranahiromod.item.RubyToolPickaxeItem;
import net.mcreator.ranahiromod.item.RubyToolHoeItem;
import net.mcreator.ranahiromod.item.RubyToolAxeItem;
import net.mcreator.ranahiromod.item.RubyItem;
import net.mcreator.ranahiromod.item.RubyArmorArmorItem;
import net.mcreator.ranahiromod.item.RiceballItem;
import net.mcreator.ranahiromod.item.RicePlantItem;
import net.mcreator.ranahiromod.item.RiceItemItem;
import net.mcreator.ranahiromod.item.RiceItem;
import net.mcreator.ranahiromod.item.Rice3Item;
import net.mcreator.ranahiromod.item.Rice2Item;
import net.mcreator.ranahiromod.item.RedBeansItemItem;
import net.mcreator.ranahiromod.item.RanazmaniumIngotItem;
import net.mcreator.ranahiromod.item.RanahiroSwordItem;
import net.mcreator.ranahiromod.item.RanahiroPowerItem;
import net.mcreator.ranahiromod.item.RanahiroPlateArmorItem;
import net.mcreator.ranahiromod.item.RanahiroMeatItem;
import net.mcreator.ranahiromod.item.RanahiroItem;
import net.mcreator.ranahiromod.item.RanahiroIngotItem;
import net.mcreator.ranahiromod.item.RanaEnergyItem;
import net.mcreator.ranahiromod.item.PrivateBottleItem;
import net.mcreator.ranahiromod.item.PizzaItem;
import net.mcreator.ranahiromod.item.PinkDiamondtSwordItem;
import net.mcreator.ranahiromod.item.PinkDiamondtShovelItem;
import net.mcreator.ranahiromod.item.PinkDiamondtPickaxeItem;
import net.mcreator.ranahiromod.item.PinkDiamondtHoeItem;
import net.mcreator.ranahiromod.item.PinkDiamondtAxeItem;
import net.mcreator.ranahiromod.item.PinkDiamondItem;
import net.mcreator.ranahiromod.item.PhotonSwordItem;
import net.mcreator.ranahiromod.item.PhotonShotItem;
import net.mcreator.ranahiromod.item.PhotonSeekerItem;
import net.mcreator.ranahiromod.item.OverHealingWandItem;
import net.mcreator.ranahiromod.item.OnihiroItemItem;
import net.mcreator.ranahiromod.item.OkonomiyakiItem;
import net.mcreator.ranahiromod.item.Okonomiyaki2Item;
import net.mcreator.ranahiromod.item.NoriItem;
import net.mcreator.ranahiromod.item.NetherriteShortSwordItem;
import net.mcreator.ranahiromod.item.MysteriousDocumentItem;
import net.mcreator.ranahiromod.item.MottieHammerItem;
import net.mcreator.ranahiromod.item.Mottie0717PowerItem;
import net.mcreator.ranahiromod.item.MoneyBulletItem;
import net.mcreator.ranahiromod.item.MochiItem;
import net.mcreator.ranahiromod.item.MochiExplodeBulletItem;
import net.mcreator.ranahiromod.item.MochiBulletItem;
import net.mcreator.ranahiromod.item.MiningDimensionItem;
import net.mcreator.ranahiromod.item.MelamainRodItem;
import net.mcreator.ranahiromod.item.Melamain3rdAmmoItem;
import net.mcreator.ranahiromod.item.MechanismArmorItem;
import net.mcreator.ranahiromod.item.Maruchi100SwordItem;
import net.mcreator.ranahiromod.item.LavarItem;
import net.mcreator.ranahiromod.item.LavahiroItemItem;
import net.mcreator.ranahiromod.item.LargeHealingWandItem;
import net.mcreator.ranahiromod.item.KeyItem;
import net.mcreator.ranahiromod.item.KashiwaMochiItem;
import net.mcreator.ranahiromod.item.IronShortSwordItem;
import net.mcreator.ranahiromod.item.IronPickaxeBulletItem;
import net.mcreator.ranahiromod.item.InfinityEatPowerItem;
import net.mcreator.ranahiromod.item.HoroshaBackArmorItem;
import net.mcreator.ranahiromod.item.HolySwordItem;
import net.mcreator.ranahiromod.item.HealingWandItem;
import net.mcreator.ranahiromod.item.GroundhiroItemItem;
import net.mcreator.ranahiromod.item.GroundItem;
import net.mcreator.ranahiromod.item.GoldenShortSwordItem;
import net.mcreator.ranahiromod.item.GalradnullItem;
import net.mcreator.ranahiromod.item.GalradItem;
import net.mcreator.ranahiromod.item.FossilaoipowerItem;
import net.mcreator.ranahiromod.item.FossilaoiSwordItemItem;
import net.mcreator.ranahiromod.item.FossilaoiBowItemItem;
import net.mcreator.ranahiromod.item.FlashLightsItem;
import net.mcreator.ranahiromod.item.FarionSwordNullItem;
import net.mcreator.ranahiromod.item.FarionSwordItem;
import net.mcreator.ranahiromod.item.FarionGunNullItem;
import net.mcreator.ranahiromod.item.FarionGunItem;
import net.mcreator.ranahiromod.item.FarionGun3Item;
import net.mcreator.ranahiromod.item.FarionGun2Item;
import net.mcreator.ranahiromod.item.FarionGun1Item;
import net.mcreator.ranahiromod.item.EpicDownSwordItem;
import net.mcreator.ranahiromod.item.EpicDownSpearItem;
import net.mcreator.ranahiromod.item.EpicDownBattleAxeItem;
import net.mcreator.ranahiromod.item.EnergyRifleItem;
import net.mcreator.ranahiromod.item.EmeraldArmorArmorItem;
import net.mcreator.ranahiromod.item.DragrItem;
import net.mcreator.ranahiromod.item.DragonhiroWingItem;
import net.mcreator.ranahiromod.item.DragonhiroItemItem;
import net.mcreator.ranahiromod.item.DragonSwordItem;
import net.mcreator.ranahiromod.item.DragonHalberdItem;
import net.mcreator.ranahiromod.item.DragonFireballWandItem;
import net.mcreator.ranahiromod.item.DorayakiItem;
import net.mcreator.ranahiromod.item.DivineRanaReinforcedItem;
import net.mcreator.ranahiromod.item.DivineRanaForceItem;
import net.mcreator.ranahiromod.item.DiamondShortSwordItem;
import net.mcreator.ranahiromod.item.DevilSwordItem;
import net.mcreator.ranahiromod.item.DevilEyeArmorItem;
import net.mcreator.ranahiromod.item.DemerItem;
import net.mcreator.ranahiromod.item.DamageSwordItem;
import net.mcreator.ranahiromod.item.DEVStickItem;
import net.mcreator.ranahiromod.item.Crystal_toolSwordItem;
import net.mcreator.ranahiromod.item.Crystal_toolShovelItem;
import net.mcreator.ranahiromod.item.Crystal_toolPickaxeItem;
import net.mcreator.ranahiromod.item.Crystal_toolAxeItem;
import net.mcreator.ranahiromod.item.CrystalItem;
import net.mcreator.ranahiromod.item.CrystalArmorArmorItem;
import net.mcreator.ranahiromod.item.Bosshiro2WingItem;
import net.mcreator.ranahiromod.item.BlazeWandItem;
import net.mcreator.ranahiromod.item.BarrierBreakerItem;
import net.mcreator.ranahiromod.item.ArrowWandItem;
import net.mcreator.ranahiromod.item.AdvpickaxeItem;
import net.mcreator.ranahiromod.RanahiromodMod;

public class RanahiromodModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, RanahiromodMod.MODID);
	public static final RegistryObject<Item> RUBY = REGISTRY.register("ruby", () -> new RubyItem());
	public static final RegistryObject<Item> RANAHIRO = REGISTRY.register("ranahiro", () -> new RanahiroItem());
	public static final RegistryObject<Item> SAPPHIRE = REGISTRY.register("sapphire", () -> new SapphireItem());
	public static final RegistryObject<Item> RUBY_ORE = block(RanahiromodModBlocks.RUBY_ORE);
	public static final RegistryObject<Item> SAPPHIRE_ORE = block(RanahiromodModBlocks.SAPPHIRE_ORE);
	public static final RegistryObject<Item> RUBY_TOOL_PICKAXE = REGISTRY.register("ruby_tool_pickaxe", () -> new RubyToolPickaxeItem());
	public static final RegistryObject<Item> RUBY_TOOL_AXE = REGISTRY.register("ruby_tool_axe", () -> new RubyToolAxeItem());
	public static final RegistryObject<Item> RUBY_TOOL_SWORD = REGISTRY.register("ruby_tool_sword", () -> new RubyToolSwordItem());
	public static final RegistryObject<Item> RUBY_TOOL_SHOVEL = REGISTRY.register("ruby_tool_shovel", () -> new RubyToolShovelItem());
	public static final RegistryObject<Item> RUBY_TOOL_HOE = REGISTRY.register("ruby_tool_hoe", () -> new RubyToolHoeItem());
	public static final RegistryObject<Item> SAPPHIRE_TOOL_PICKAXE = REGISTRY.register("sapphire_tool_pickaxe", () -> new SapphireToolPickaxeItem());
	public static final RegistryObject<Item> SAPPHIRE_TOOL_AXE = REGISTRY.register("sapphire_tool_axe", () -> new SapphireToolAxeItem());
	public static final RegistryObject<Item> SAPPHIRE_TOOL_SWORD = REGISTRY.register("sapphire_tool_sword", () -> new SapphireToolSwordItem());
	public static final RegistryObject<Item> SAPPHIRE_TOOL_SHOVEL = REGISTRY.register("sapphire_tool_shovel", () -> new SapphireToolShovelItem());
	public static final RegistryObject<Item> SAPPHIRE_TOOL_HOE = REGISTRY.register("sapphire_tool_hoe", () -> new SapphireToolHoeItem());
	public static final RegistryObject<Item> PINK_DIAMOND = REGISTRY.register("pink_diamond", () -> new PinkDiamondItem());
	public static final RegistryObject<Item> PINK_DIAMOND_ORE = block(RanahiromodModBlocks.PINK_DIAMOND_ORE);
	public static final RegistryObject<Item> PINK_DIAMONDT_PICKAXE = REGISTRY.register("pink_diamondt_pickaxe", () -> new PinkDiamondtPickaxeItem());
	public static final RegistryObject<Item> PINK_DIAMONDT_AXE = REGISTRY.register("pink_diamondt_axe", () -> new PinkDiamondtAxeItem());
	public static final RegistryObject<Item> PINK_DIAMONDT_SWORD = REGISTRY.register("pink_diamondt_sword", () -> new PinkDiamondtSwordItem());
	public static final RegistryObject<Item> PINK_DIAMONDT_SHOVEL = REGISTRY.register("pink_diamondt_shovel", () -> new PinkDiamondtShovelItem());
	public static final RegistryObject<Item> PINK_DIAMONDT_HOE = REGISTRY.register("pink_diamondt_hoe", () -> new PinkDiamondtHoeItem());
	public static final RegistryObject<Item> SWORD_OF_BOSSHIRO = REGISTRY.register("sword_of_bosshiro", () -> new SwordOfBosshiroItem());
	public static final RegistryObject<Item> SUMAHIRO_PHONE = REGISTRY.register("sumahiro_phone", () -> new SumahiroPhoneItem());
	public static final RegistryObject<Item> CRYSTAL = REGISTRY.register("crystal", () -> new CrystalItem());
	public static final RegistryObject<Item> CRYSTAL_ORE = block(RanahiromodModBlocks.CRYSTAL_ORE);
	public static final RegistryObject<Item> RUBY_ARMOR_ARMOR_HELMET = REGISTRY.register("ruby_armor_armor_helmet", () -> new RubyArmorArmorItem.Helmet());
	public static final RegistryObject<Item> RUBY_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("ruby_armor_armor_chestplate", () -> new RubyArmorArmorItem.Chestplate());
	public static final RegistryObject<Item> RUBY_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("ruby_armor_armor_leggings", () -> new RubyArmorArmorItem.Leggings());
	public static final RegistryObject<Item> RUBY_ARMOR_ARMOR_BOOTS = REGISTRY.register("ruby_armor_armor_boots", () -> new RubyArmorArmorItem.Boots());
	public static final RegistryObject<Item> SAPPHIRE_ARMOR_ARMOR_HELMET = REGISTRY.register("sapphire_armor_armor_helmet", () -> new SapphireArmorArmorItem.Helmet());
	public static final RegistryObject<Item> SAPPHIRE_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("sapphire_armor_armor_chestplate", () -> new SapphireArmorArmorItem.Chestplate());
	public static final RegistryObject<Item> SAPPHIRE_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("sapphire_armor_armor_leggings", () -> new SapphireArmorArmorItem.Leggings());
	public static final RegistryObject<Item> SAPPHIRE_ARMOR_ARMOR_BOOTS = REGISTRY.register("sapphire_armor_armor_boots", () -> new SapphireArmorArmorItem.Boots());
	public static final RegistryObject<Item> CRYSTAL_ARMOR_ARMOR_HELMET = REGISTRY.register("crystal_armor_armor_helmet", () -> new CrystalArmorArmorItem.Helmet());
	public static final RegistryObject<Item> CRYSTAL_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("crystal_armor_armor_chestplate", () -> new CrystalArmorArmorItem.Chestplate());
	public static final RegistryObject<Item> CRYSTAL_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("crystal_armor_armor_leggings", () -> new CrystalArmorArmorItem.Leggings());
	public static final RegistryObject<Item> CRYSTAL_ARMOR_ARMOR_BOOTS = REGISTRY.register("crystal_armor_armor_boots", () -> new CrystalArmorArmorItem.Boots());
	public static final RegistryObject<Item> LAVAHIRO_ITEM = REGISTRY.register("lavahiro_item", () -> new LavahiroItemItem());
	public static final RegistryObject<Item> RICE_PLANT_STAGE_0 = block(RanahiromodModBlocks.RICE_PLANT_STAGE_0);
	public static final RegistryObject<Item> RICE_PLANT_STAGE_1 = block(RanahiromodModBlocks.RICE_PLANT_STAGE_1);
	public static final RegistryObject<Item> RICE_PLANT_STAGE_2 = block(RanahiromodModBlocks.RICE_PLANT_STAGE_2);
	public static final RegistryObject<Item> RICE_PLANT_STAGE_3 = block(RanahiromodModBlocks.RICE_PLANT_STAGE_3);
	public static final RegistryObject<Item> RICE_PLANT_STAGE_4 = block(RanahiromodModBlocks.RICE_PLANT_STAGE_4);
	public static final RegistryObject<Item> RICE_PLANT_STAGE_5 = block(RanahiromodModBlocks.RICE_PLANT_STAGE_5);
	public static final RegistryObject<Item> RICE_PLANT_STAGE_6 = block(RanahiromodModBlocks.RICE_PLANT_STAGE_6);
	public static final RegistryObject<Item> RICE_PLANT_STAGE_7 = block(RanahiromodModBlocks.RICE_PLANT_STAGE_7);
	public static final RegistryObject<Item> RICE_ITEM = REGISTRY.register("rice_item", () -> new RiceItemItem());
	public static final RegistryObject<Item> RICE_PLANT = REGISTRY.register("rice_plant", () -> new RicePlantItem());
	public static final RegistryObject<Item> WET_NORI = REGISTRY.register("wet_nori", () -> new WetNoriItem());
	public static final RegistryObject<Item> NORI = REGISTRY.register("nori", () -> new NoriItem());
	public static final RegistryObject<Item> CRYSTAL_TOOL_PICKAXE = REGISTRY.register("crystal_tool_pickaxe", () -> new Crystal_toolPickaxeItem());
	public static final RegistryObject<Item> CRYSTAL_TOOL_AXE = REGISTRY.register("crystal_tool_axe", () -> new Crystal_toolAxeItem());
	public static final RegistryObject<Item> CRYSTAL_TOOL_SWORD = REGISTRY.register("crystal_tool_sword", () -> new Crystal_toolSwordItem());
	public static final RegistryObject<Item> CRYSTAL_TOOL_SHOVEL = REGISTRY.register("crystal_tool_shovel", () -> new Crystal_toolShovelItem());
	public static final RegistryObject<Item> WATERHIRO_ITEM = REGISTRY.register("waterhiro_item", () -> new WaterhiroItemItem());
	public static final RegistryObject<Item> WINDHIRO_ITEM = REGISTRY.register("windhiro_item", () -> new WindhiroItemItem());
	public static final RegistryObject<Item> FLASH_LIGHT = REGISTRY.register("flash_light", () -> new FlashLightsItem());
	public static final RegistryObject<Item> FLASHLIGHT_BLOCK = block(RanahiromodModBlocks.FLASHLIGHT_BLOCK);
	public static final RegistryObject<Item> LAVAHIRO_SUMMON_BLOCK = block(RanahiromodModBlocks.LAVAHIRO_SUMMON_BLOCK);
	public static final RegistryObject<Item> HEALING_WAND = REGISTRY.register("healing_wand", () -> new HealingWandItem());
	public static final RegistryObject<Item> WATERHIRO_SPAWN_EGG = REGISTRY.register("waterhiro_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.WATERHIRO, -10066177, -16777063, new Item.Properties()));
	public static final RegistryObject<Item> WINDHIRO_SPAWN_EGG = REGISTRY.register("windhiro_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.WINDHIRO, -10027162, -16724992, new Item.Properties()));
	public static final RegistryObject<Item> DRAGONHIRO_SPAWN_EGG = REGISTRY.register("dragonhiro_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.DRAGONHIRO, -6710887, -10066330, new Item.Properties()));
	public static final RegistryObject<Item> ONIHIRO_SPAWN_EGG = REGISTRY.register("onihiro_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.ONIHIRO, -3407872, -10092544, new Item.Properties()));
	public static final RegistryObject<Item> BOSSHIRO_SPAWN_EGG = REGISTRY.register("bosshiro_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.BOSSHIRO, -16777216, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> DRAGONHIRO_ITEM = REGISTRY.register("dragonhiro_item", () -> new DragonhiroItemItem());
	public static final RegistryObject<Item> ONIHIRO_ITEM = REGISTRY.register("onihiro_item", () -> new OnihiroItemItem());
	public static final RegistryObject<Item> RICE = REGISTRY.register("rice", () -> new RiceItem());
	public static final RegistryObject<Item> RICE_2 = REGISTRY.register("rice_2", () -> new Rice2Item());
	public static final RegistryObject<Item> RICE_3 = REGISTRY.register("rice_3", () -> new Rice3Item());
	public static final RegistryObject<Item> RICEBALL = REGISTRY.register("riceball", () -> new RiceballItem());
	public static final RegistryObject<Item> DRAGONHIRO_WING_CHESTPLATE = REGISTRY.register("dragonhiro_wing_chestplate", () -> new DragonhiroWingItem.Chestplate());
	public static final RegistryObject<Item> WARDENHIRO_SPAWN_EGG = REGISTRY.register("wardenhiro_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.WARDENHIRO, -16750951, -16777165, new Item.Properties()));
	public static final RegistryObject<Item> FOSSILAOI_SPAWN_EGG = REGISTRY.register("fossilaoi_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.FOSSILAOI, -3355444, -13369549, new Item.Properties()));
	public static final RegistryObject<Item> BOSSHIRO_2_WING_CHESTPLATE = REGISTRY.register("bosshiro_2_wing_chestplate", () -> new Bosshiro2WingItem.Chestplate());
	public static final RegistryObject<Item> BOLTHIRO_ITEM = REGISTRY.register("bolthiro_item", () -> new VolthiroItemItem());
	public static final RegistryObject<Item> FOSSILAOI_SWORD_ITEM = REGISTRY.register("fossilaoi_sword_item", () -> new FossilaoiSwordItemItem());
	public static final RegistryObject<Item> FOSSILAOI_BOW_ITEM = REGISTRY.register("fossilaoi_bow_item", () -> new FossilaoiBowItemItem());
	public static final RegistryObject<Item> BOLTHIRO_SPAWN_EGG = REGISTRY.register("bolthiro_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.BOLTHIRO, -13421773, -256, new Item.Properties()));
	public static final RegistryObject<Item> BLAZE_WAND = REGISTRY.register("blaze_wand", () -> new BlazeWandItem());
	public static final RegistryObject<Item> DRAGON_FIREBALL_WAND = REGISTRY.register("dragon_fireball_wand", () -> new DragonFireballWandItem());
	public static final RegistryObject<Item> MOCHI = REGISTRY.register("mochi", () -> new MochiItem());
	public static final RegistryObject<Item> MOTTIE_HAMMER = REGISTRY.register("mottie_hammer", () -> new MottieHammerItem());
	public static final RegistryObject<Item> MOTTIE_0717_SPAWN_EGG = REGISTRY.register("mottie_0717_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.MOTTIE_0717, -1, -26368, new Item.Properties()));
	public static final RegistryObject<Item> SK_LINER_5077_SPAWN_EGG = REGISTRY.register("sk_liner_5077_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.SK_LINER_5077, -10027009, -16737793, new Item.Properties()));
	public static final RegistryObject<Item> SK_LINER_5077_BLADE = REGISTRY.register("sk_liner_5077_blade", () -> new SKLiner5077BladeItem());
	public static final RegistryObject<Item> DEV_STICK = REGISTRY.register("dev_stick", () -> new DEVStickItem());
	public static final RegistryObject<Item> VAZAFILA_SPAWN_EGG = REGISTRY.register("vazafila_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.VAZAFILA, -13421773, -26368, new Item.Properties()));
	public static final RegistryObject<Item> VAZAFILA_SWORD = REGISTRY.register("vazafila_sword", () -> new VazafilaSwordItem());
	public static final RegistryObject<Item> WARDENHIRO_ITEM = REGISTRY.register("wardenhiro_item", () -> new WardenhiroItemItem());
	public static final RegistryObject<Item> FOSSILAOIPOWER = REGISTRY.register("fossilaoipower", () -> new FossilaoipowerItem());
	public static final RegistryObject<Item> SK_LINER_5077_POWER = REGISTRY.register("sk_liner_5077_power", () -> new SKLiner5077PowerItem());
	public static final RegistryObject<Item> MOTTIE_0717_POWER = REGISTRY.register("mottie_0717_power", () -> new Mottie0717PowerItem());
	public static final RegistryObject<Item> PHOTON_SWORD = REGISTRY.register("photon_sword", () -> new PhotonSwordItem());
	public static final RegistryObject<Item> KEY_EMPTY_BLOCK = block(RanahiromodModBlocks.KEY_EMPTY_BLOCK);
	public static final RegistryObject<Item> KEY_FILL_BLOCK = block(RanahiromodModBlocks.KEY_FILL_BLOCK);
	public static final RegistryObject<Item> KEY_HARDENED_GLASS = block(RanahiromodModBlocks.KEY_HARDENED_GLASS);
	public static final RegistryObject<Item> KEY = REGISTRY.register("key", () -> new KeyItem());
	public static final RegistryObject<Item> BARRIER_BREAKER = REGISTRY.register("barrier_breaker", () -> new BarrierBreakerItem());
	public static final RegistryObject<Item> TOPAZ = REGISTRY.register("topaz", () -> new TopazItem());
	public static final RegistryObject<Item> TOPAZ_TOOL_ARMOR_HELMET = REGISTRY.register("topaz_tool_armor_helmet", () -> new Topaz_toolArmorItem.Helmet());
	public static final RegistryObject<Item> TOPAZ_TOOL_ARMOR_CHESTPLATE = REGISTRY.register("topaz_tool_armor_chestplate", () -> new Topaz_toolArmorItem.Chestplate());
	public static final RegistryObject<Item> TOPAZ_TOOL_ARMOR_LEGGINGS = REGISTRY.register("topaz_tool_armor_leggings", () -> new Topaz_toolArmorItem.Leggings());
	public static final RegistryObject<Item> TOPAZ_TOOL_ARMOR_BOOTS = REGISTRY.register("topaz_tool_armor_boots", () -> new Topaz_toolArmorItem.Boots());
	public static final RegistryObject<Item> EMERALD_ARMOR_ARMOR_HELMET = REGISTRY.register("emerald_armor_armor_helmet", () -> new EmeraldArmorArmorItem.Helmet());
	public static final RegistryObject<Item> EMERALD_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("emerald_armor_armor_chestplate", () -> new EmeraldArmorArmorItem.Chestplate());
	public static final RegistryObject<Item> EMERALD_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("emerald_armor_armor_leggings", () -> new EmeraldArmorArmorItem.Leggings());
	public static final RegistryObject<Item> EMERALD_ARMOR_ARMOR_BOOTS = REGISTRY.register("emerald_armor_armor_boots", () -> new EmeraldArmorArmorItem.Boots());
	public static final RegistryObject<Item> VAZAFILA_POWER = REGISTRY.register("vazafila_power", () -> new VazafilaPowerItem());
	public static final RegistryObject<Item> PIROKICHIHAWAII_SPAWN_EGG = REGISTRY.register("pirokichihawaii_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.PIROKICHIHAWAII, -6710887, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> RANAHIRO_SWORD = REGISTRY.register("ranahiro_sword", () -> new RanahiroSwordItem());
	public static final RegistryObject<Item> WEAPONHIRO_ITEM = REGISTRY.register("weaponhiro_item", () -> new WeaponhiroItemItem());
	public static final RegistryObject<Item> RANDOM_DYE_GENERATOR = REGISTRY.register("random_dye_generator", () -> new SmasherItem());
	public static final RegistryObject<Item> EPIC_DOWN_ZOMBIE_SPAWN_EGG = REGISTRY.register("epic_down_zombie_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.EPIC_DOWN_ZOMBIE, -13395712, -10027162, new Item.Properties()));
	public static final RegistryObject<Item> EPIC_DOWN_SWORD = REGISTRY.register("epic_down_sword", () -> new EpicDownSwordItem());
	public static final RegistryObject<Item> EPIC_DOWN_BATTLE_AXE = REGISTRY.register("epic_down_battle_axe", () -> new EpicDownBattleAxeItem());
	public static final RegistryObject<Item> EPIC_DOWN_SPEAR = REGISTRY.register("epic_down_spear", () -> new EpicDownSpearItem());
	public static final RegistryObject<Item> UNDEFINED_MEAT = REGISTRY.register("undefined_meat", () -> new UndefinedMeatItem());
	public static final RegistryObject<Item> LAVANICAL_GOLEM_SPAWN_EGG = REGISTRY.register("lavanical_golem_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.LAVANICAL_GOLEM, -52429, -65536, new Item.Properties()));
	public static final RegistryObject<Item> TOPAZ_ORE = block(RanahiromodModBlocks.TOPAZ_ORE);
	public static final RegistryObject<Item> YUU_2434_SPAWN_EGG = REGISTRY.register("yuu_2434_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.YUU_2434, -13421773, -1, new Item.Properties()));
	public static final RegistryObject<Item> MELAMAIN_0105_SPAWN_EGG = REGISTRY.register("melamain_0105_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.MELAMAIN_0105, -10092493, -6750055, new Item.Properties()));
	public static final RegistryObject<Item> SUN_ROD = REGISTRY.register("sun_rod", () -> new SunRodItem());
	public static final RegistryObject<Item> MELAMAIN_ROD = REGISTRY.register("melamain_rod", () -> new MelamainRodItem());
	public static final RegistryObject<Item> MYSTERIOUS_DOCUMENT = REGISTRY.register("mysterious_document", () -> new MysteriousDocumentItem());
	public static final RegistryObject<Item> SEALED_MYSTERIOUS_DOCUMENT = REGISTRY.register("sealed_mysterious_document", () -> new SealedMysteriouDocumentItem());
	public static final RegistryObject<Item> BOSSHIRO_3_CODE_PHOENIX_SPAWN_EGG = REGISTRY.register("bosshiro_3_code_phoenix_spawn_egg",
			() -> new ForgeSpawnEggItem(RanahiromodModEntities.BOSSHIRO_3_CODE_PHOENIX, -16777216, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> GROUNDHIRO_SPAWN_EGG = REGISTRY.register("groundhiro_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.GROUNDHIRO, -3381760, -39424, new Item.Properties()));
	public static final RegistryObject<Item> FARION_SWORD = REGISTRY.register("farion_sword", () -> new FarionSwordItem());
	public static final RegistryObject<Item> EPIC_DOWN_SKELETON_SPAWN_EGG = REGISTRY.register("epic_down_skeleton_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.EPIC_DOWN_SKELETON, -1, -3407668, new Item.Properties()));
	public static final RegistryObject<Item> STRANGE_INK = REGISTRY.register("strange_ink", () -> new StrangeInkItem());
	public static final RegistryObject<Item> ADVPICKAXE = REGISTRY.register("advpickaxe", () -> new AdvpickaxeItem());
	public static final RegistryObject<Item> WOODEN_SHORT_SWORD = REGISTRY.register("wooden_short_sword", () -> new WoodenShortSwordItem());
	public static final RegistryObject<Item> STONE_SHORT_SWORD = REGISTRY.register("stone_short_sword", () -> new StoneShortSwordItem());
	public static final RegistryObject<Item> IRON_SHORT_SWORD = REGISTRY.register("iron_short_sword", () -> new IronShortSwordItem());
	public static final RegistryObject<Item> GOLDEN_SHORT_SWORD = REGISTRY.register("golden_short_sword", () -> new GoldenShortSwordItem());
	public static final RegistryObject<Item> DIAMOND_SHORT_SWORD = REGISTRY.register("diamond_short_sword", () -> new DiamondShortSwordItem());
	public static final RegistryObject<Item> NETHERRITE_SHORT_SWORD = REGISTRY.register("netherrite_short_sword", () -> new NetherriteShortSwordItem());
	public static final RegistryObject<Item> MINER_SKELETON_SPAWN_EGG = REGISTRY.register("miner_skeleton_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.MINER_SKELETON, -1, -10066432, new Item.Properties()));
	public static final RegistryObject<Item> MARUCHI_100_SWORD = REGISTRY.register("maruchi_100_sword", () -> new Maruchi100SwordItem());
	public static final RegistryObject<Item> DRAGON_SWORD = REGISTRY.register("dragon_sword", () -> new DragonSwordItem());
	public static final RegistryObject<Item> DRAGON_HALBERD = REGISTRY.register("dragon_halberd", () -> new DragonHalberdItem());
	public static final RegistryObject<Item> DRAGONHIRO_KNIGHT_SPAWN_EGG = REGISTRY.register("dragonhiro_knight_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.DRAGONHIRO_KNIGHT, -6710887, -13395712, new Item.Properties()));
	public static final RegistryObject<Item> SEAHOUSE_NIGHTMARE_SPAWN_EGG = REGISTRY.register("seahouse_nightmare_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.SEAHOUSE_NIGHTMARE, -16777063, -65536, new Item.Properties()));
	public static final RegistryObject<Item> INFINITY_EAT_POWER = REGISTRY.register("infinity_eat_power", () -> new InfinityEatPowerItem());
	public static final RegistryObject<Item> TOPAZ_TOOL_PICKAXE = REGISTRY.register("topaz_tool_pickaxe", () -> new Topaz_toolPickaxeItem());
	public static final RegistryObject<Item> TOPAZ_TOOL_AXE = REGISTRY.register("topaz_tool_axe", () -> new Topaz_toolAxeItem());
	public static final RegistryObject<Item> TOPAZ_TOOL_SWORD = REGISTRY.register("topaz_tool_sword", () -> new Topaz_toolSwordItem());
	public static final RegistryObject<Item> TOPAZ_TOOL_SHOVEL = REGISTRY.register("topaz_tool_shovel", () -> new Topaz_toolShovelItem());
	public static final RegistryObject<Item> TOPAZ_TOOL_HOE = REGISTRY.register("topaz_tool_hoe", () -> new Topaz_toolHoeItem());
	public static final RegistryObject<Item> RANAHIRO_INGOT = REGISTRY.register("ranahiro_ingot", () -> new RanahiroIngotItem());
	public static final RegistryObject<Item> RANAHIRO_PLATE_ARMOR_HELMET = REGISTRY.register("ranahiro_plate_armor_helmet", () -> new RanahiroPlateArmorItem.Helmet());
	public static final RegistryObject<Item> RANAHIRO_PLATE_ARMOR_CHESTPLATE = REGISTRY.register("ranahiro_plate_armor_chestplate", () -> new RanahiroPlateArmorItem.Chestplate());
	public static final RegistryObject<Item> RANAHIRO_PLATE_ARMOR_LEGGINGS = REGISTRY.register("ranahiro_plate_armor_leggings", () -> new RanahiroPlateArmorItem.Leggings());
	public static final RegistryObject<Item> RANAHIRO_PLATE_ARMOR_BOOTS = REGISTRY.register("ranahiro_plate_armor_boots", () -> new RanahiroPlateArmorItem.Boots());
	public static final RegistryObject<Item> GALE_SLASHER_SPAWN_EGG = REGISTRY.register("gale_slasher_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.GALE_SLASHER, -3342388, -10027162, new Item.Properties()));
	public static final RegistryObject<Item> RANAZMANIUM_INGOT = REGISTRY.register("ranazmanium_ingot", () -> new RanazmaniumIngotItem());
	public static final RegistryObject<Item> BRESOLDIER_SPAWN_EGG = REGISTRY.register("bresoldier_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.BRESOLDIER, -10027162, -13395712, new Item.Properties()));
	public static final RegistryObject<Item> DIVINE_RANA_FORCE = REGISTRY.register("divine_rana_force", () -> new DivineRanaForceItem());
	public static final RegistryObject<Item> SOUL_GRIEF_SWORD = REGISTRY.register("soul_grief_sword", () -> new SoulGriefSwordItem());
	public static final RegistryObject<Item> SOUL_GRIEF_INGOT = REGISTRY.register("soul_grief_ingot", () -> new SoulGriefIngotItem());
	public static final RegistryObject<Item> OVER_HARDENED_STONE = block(RanahiromodModBlocks.OVER_HARDENED_STONE);
	public static final RegistryObject<Item> SOUL_BLOCK = block(RanahiromodModBlocks.SOUL_BLOCK);
	public static final RegistryObject<Item> SOUL_INGOT = REGISTRY.register("soul_ingot", () -> new SoulIngotItem());
	public static final RegistryObject<Item> MECHANISM_ARMOR_HELMET = REGISTRY.register("mechanism_armor_helmet", () -> new MechanismArmorItem.Helmet());
	public static final RegistryObject<Item> MECHANISM_ARMOR_CHESTPLATE = REGISTRY.register("mechanism_armor_chestplate", () -> new MechanismArmorItem.Chestplate());
	public static final RegistryObject<Item> MECHANISM_ARMOR_LEGGINGS = REGISTRY.register("mechanism_armor_leggings", () -> new MechanismArmorItem.Leggings());
	public static final RegistryObject<Item> MECHANISM_ARMOR_BOOTS = REGISTRY.register("mechanism_armor_boots", () -> new MechanismArmorItem.Boots());
	public static final RegistryObject<Item> DIVINE_RANA_REINFORCED = REGISTRY.register("divine_rana_reinforced", () -> new DivineRanaReinforcedItem());
	public static final RegistryObject<Item> LAVAHIRO_SPAWN_EGG = REGISTRY.register("lavahiro_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.LAVAHIRO, -65536, -52429, new Item.Properties()));
	public static final RegistryObject<Item> GENERAL_SKELETON_SPAWN_EGG = REGISTRY.register("general_skeleton_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.GENERAL_SKELETON, -13434625, -52429, new Item.Properties()));
	public static final RegistryObject<Item> GENERAL_WITHER_SKELETON_SPAWN_EGG = REGISTRY.register("general_wither_skeleton_spawn_egg",
			() -> new ForgeSpawnEggItem(RanahiromodModEntities.GENERAL_WITHER_SKELETON, -13434625, -52429, new Item.Properties()));
	public static final RegistryObject<Item> EPIC_DOWN_CREEPER_SPAWN_EGG = REGISTRY.register("epic_down_creeper_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.EPIC_DOWN_CREEPER, -13395712, -10027162, new Item.Properties()));
	public static final RegistryObject<Item> STRUCTURE_SUMMON_BLOCK = block(RanahiromodModBlocks.STRUCTURE_SUMMON_BLOCK);
	public static final RegistryObject<Item> HYPOCRITE_SPAWN_EGG = REGISTRY.register("hypocrite_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.HYPOCRITE, -6710887, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> SWEEP_ITEM = REGISTRY.register("sweep_item", () -> new SweepItemItem());
	public static final RegistryObject<Item> SPLADOT_SPAWN_EGG = REGISTRY.register("spladot_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.SPLADOT, -10027009, -3407617, new Item.Properties()));
	public static final RegistryObject<Item> SPLADOT_ROD = REGISTRY.register("spladot_rod", () -> new SpladotRodItem());
	public static final RegistryObject<Item> SPLADOT_POWER = REGISTRY.register("spladot_power", () -> new SpladotPowerItem());
	public static final RegistryObject<Item> RANAHIRO_POWER = REGISTRY.register("ranahiro_power", () -> new RanahiroPowerItem());
	public static final RegistryObject<Item> VAZAFILA_KATANA = REGISTRY.register("vazafila_katana", () -> new VazafilaKatanaItem());
	public static final RegistryObject<Item> WIND_MAGIC = REGISTRY.register("wind_magic", () -> new WindMagicItem());
	public static final RegistryObject<Item> HIROMARUTV_SPAWN_EGG = REGISTRY.register("hiromarutv_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.HIROMARUTV, -65536, -16776961, new Item.Properties()));
	public static final RegistryObject<Item> HOROSHA_BACK_ARMOR = REGISTRY.register("horosha_back_armor", () -> new HoroshaBackArmorItem());
	public static final RegistryObject<Item> HOLY_SWORD = REGISTRY.register("holy_sword", () -> new HolySwordItem());
	public static final RegistryObject<Item> DEVIL_SWORD = REGISTRY.register("devil_sword", () -> new DevilSwordItem());
	public static final RegistryObject<Item> YOTO = REGISTRY.register("yoto", () -> new YotoItem());
	public static final RegistryObject<Item> LARGE_HEALING_WAND = REGISTRY.register("large_healing_wand", () -> new LargeHealingWandItem());
	public static final RegistryObject<Item> DEBUG_SUMMON_SPAWN_EGG = REGISTRY.register("debug_summon_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.DEBUG_SUMMON, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> EPIC_DOWN_ENDERMAN_SPAWN_EGG = REGISTRY.register("epic_down_enderman_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.EPIC_DOWN_ENDERMAN, -10092442, -65281, new Item.Properties()));
	public static final RegistryObject<Item> KNIGHT_OF_LIGHTNING_SPAWN_EGG = REGISTRY.register("knight_of_lightning_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.KNIGHT_OF_LIGHTNING, -256, -154, new Item.Properties()));
	public static final RegistryObject<Item> DAMAGE_SWORD = REGISTRY.register("damage_sword", () -> new DamageSwordItem());
	public static final RegistryObject<Item> RANA_ENERGY = REGISTRY.register("rana_energy", () -> new RanaEnergyItem());
	public static final RegistryObject<Item> TAICHAN_SPAWN_EGG = REGISTRY.register("taichan_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.TAICHAN, -1, -52429, new Item.Properties()));
	public static final RegistryObject<Item> WAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWAWA = REGISTRY.register("wawawawawawawawawawawawawawawawawawawawawawawawawawawawawawa",
			() -> new WawawawawawawawawawawawawawawawawawawawawawawawawawawawawawaItem());
	public static final RegistryObject<Item> JEWEL_ORE = block(RanahiromodModBlocks.JEWEL_ORE);
	public static final RegistryObject<Item> DEEPSLATE_JEWEL_ORE = block(RanahiromodModBlocks.DEEPSLATE_JEWEL_ORE);
	public static final RegistryObject<Item> EPIC_DOWN_BLAZE_SPAWN_EGG = REGISTRY.register("epic_down_blaze_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.EPIC_DOWN_BLAZE, -52378, -65281, new Item.Properties()));
	public static final RegistryObject<Item> GROUNDHIRO_ITEM = REGISTRY.register("groundhiro_item", () -> new GroundhiroItemItem());
	public static final RegistryObject<Item> SHOWCASE = block(RanahiromodModBlocks.SHOWCASE);
	public static final RegistryObject<Item> GLASS_CASE = block(RanahiromodModBlocks.GLASS_CASE);
	public static final RegistryObject<Item> LAVANICAL_TRACKER_SPAWN_EGG = REGISTRY.register("lavanical_tracker_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.LAVANICAL_TRACKER, -52429, -3394816, new Item.Properties()));
	public static final RegistryObject<Item> GALRAD = REGISTRY.register("galrad", () -> new GalradItem());
	public static final RegistryObject<Item> UNDEFINED_CREEPER_SPAWN_EGG = REGISTRY.register("undefined_creeper_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.UNDEFINED_CREEPER, -65281, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> UNDEFINED_ZOMBIE_SPAWN_EGG = REGISTRY.register("undefined_zombie_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.UNDEFINED_ZOMBIE, -65281, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> GALRADNULL = REGISTRY.register("galradnull", () -> new GalradnullItem());
	public static final RegistryObject<Item> UNDEFINED_SKELETON_SPAWN_EGG = REGISTRY.register("undefined_skeleton_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.UNDEFINED_SKELETON, -65281, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> FARION_SWORD_NULL = REGISTRY.register("farion_sword_null", () -> new FarionSwordNullItem());
	public static final RegistryObject<Item> UNDEFINED_GHAST_SPAWN_EGG = REGISTRY.register("undefined_ghast_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.UNDEFINED_GHAST, -65281, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> UNDEFINED_WITCH_SPAWN_EGG = REGISTRY.register("undefined_witch_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.UNDEFINED_WITCH, -65281, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> DOMAIN_BARRIER = block(RanahiromodModBlocks.DOMAIN_BARRIER);
	public static final RegistryObject<Item> AIR_BARIIER = block(RanahiromodModBlocks.AIR_BARIIER);
	public static final RegistryObject<Item> SPAWNER_BREAKER = REGISTRY.register("spawner_breaker", () -> new SpawnerBreakerItem());
	public static final RegistryObject<Item> MINING_DIMENSION = REGISTRY.register("mining_dimension", () -> new MiningDimensionItem());
	public static final RegistryObject<Item> MY_HOUSE_STRUCTURE_BLOCK = block(RanahiromodModBlocks.MY_HOUSE_STRUCTURE_BLOCK);
	public static final RegistryObject<Item> FIELD_STRUCUTRE_BLOCK = block(RanahiromodModBlocks.FIELD_STRUCUTRE_BLOCK);
	public static final RegistryObject<Item> MOCHI_BULLET = REGISTRY.register("mochi_bullet", () -> new MochiBulletItem());
	public static final RegistryObject<Item> MOCHI_EXPLODE_BULLET = REGISTRY.register("mochi_explode_bullet", () -> new MochiExplodeBulletItem());
	public static final RegistryObject<Item> PHOTON_SEEKER = REGISTRY.register("photon_seeker", () -> new PhotonSeekerItem());
	public static final RegistryObject<Item> PHOTON_SHOT = REGISTRY.register("photon_shot", () -> new PhotonShotItem());
	public static final RegistryObject<Item> UNDEFINED_GUN = REGISTRY.register("undefined_gun", () -> new UndefinedGunItem());
	public static final RegistryObject<Item> MELAMAIN_3RD_AMMO = REGISTRY.register("melamain_3rd_ammo", () -> new Melamain3rdAmmoItem());
	public static final RegistryObject<Item> FARION_GUN = REGISTRY.register("farion_gun", () -> new FarionGunItem());
	public static final RegistryObject<Item> FARION_GUN_1 = REGISTRY.register("farion_gun_1", () -> new FarionGun1Item());
	public static final RegistryObject<Item> FARION_GUN_2 = REGISTRY.register("farion_gun_2", () -> new FarionGun2Item());
	public static final RegistryObject<Item> FARION_GUN_3 = REGISTRY.register("farion_gun_3", () -> new FarionGun3Item());
	public static final RegistryObject<Item> MONEY_BULLET = REGISTRY.register("money_bullet", () -> new MoneyBulletItem());
	public static final RegistryObject<Item> ENERGY_RIFLE = REGISTRY.register("energy_rifle", () -> new EnergyRifleItem());
	public static final RegistryObject<Item> IRON_PICKAXE_BULLET = REGISTRY.register("iron_pickaxe_bullet", () -> new IronPickaxeBulletItem());
	public static final RegistryObject<Item> TAICHAN_BOW = REGISTRY.register("taichan_bow", () -> new TaichanBowItem());
	public static final RegistryObject<Item> FARION_GUN_NULL = REGISTRY.register("farion_gun_null", () -> new FarionGunNullItem());
	public static final RegistryObject<Item> TREASURE_CHEST_ITEM = REGISTRY.register("treasure_chest_item", () -> new TreasureChestItemItem());
	public static final RegistryObject<Item> SAKURAMOCHI = REGISTRY.register("sakuramochi", () -> new SakuramochiItem());
	public static final RegistryObject<Item> KASHIWA_MOCHI = REGISTRY.register("kashiwa_mochi", () -> new KashiwaMochiItem());
	public static final RegistryObject<Item> OKONOMIYAKI = REGISTRY.register("okonomiyaki", () -> new OkonomiyakiItem());
	public static final RegistryObject<Item> DORAYAKI = REGISTRY.register("dorayaki", () -> new DorayakiItem());
	public static final RegistryObject<Item> UNDEFINED_RAMEN = REGISTRY.register("undefined_ramen", () -> new UndefinedRamenItem());
	public static final RegistryObject<Item> ZONI = REGISTRY.register("zoni", () -> new ZoniItem());
	public static final RegistryObject<Item> YAKISOBA = REGISTRY.register("yakisoba", () -> new YakisobaItem());
	public static final RegistryObject<Item> OKONOMIYAKI_2 = REGISTRY.register("okonomiyaki_2", () -> new Okonomiyaki2Item());
	public static final RegistryObject<Item> PIZZA = REGISTRY.register("pizza", () -> new PizzaItem());
	public static final RegistryObject<Item> RANAHIRO_MEAT = REGISTRY.register("ranahiro_meat", () -> new RanahiroMeatItem());
	public static final RegistryObject<Item> RED_BEANS_ITEM = REGISTRY.register("red_beans_item", () -> new RedBeansItemItem());
	public static final RegistryObject<Item> BIG_RANAHIRO_SPAWN_EGG = REGISTRY.register("big_ranahiro_spawn_egg", () -> new ForgeSpawnEggItem(RanahiromodModEntities.BIG_RANAHIRO, -6710887, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> OVER_HEALING_WAND = REGISTRY.register("over_healing_wand", () -> new OverHealingWandItem());
	public static final RegistryObject<Item> ARROW_WAND = REGISTRY.register("arrow_wand", () -> new ArrowWandItem());
	public static final RegistryObject<Item> LAVAR = REGISTRY.register("lavar", () -> new LavarItem());
	public static final RegistryObject<Item> WATER = REGISTRY.register("water", () -> new WaterItem());
	public static final RegistryObject<Item> WINDR = REGISTRY.register("windr", () -> new WindrItem());
	public static final RegistryObject<Item> DRAGR = REGISTRY.register("dragr", () -> new DragrItem());
	public static final RegistryObject<Item> DEMER = REGISTRY.register("demer", () -> new DemerItem());
	public static final RegistryObject<Item> VOLTR = REGISTRY.register("voltr", () -> new VoltrItem());
	public static final RegistryObject<Item> WARDER = REGISTRY.register("warder", () -> new WarderItem());
	public static final RegistryObject<Item> GROUND = REGISTRY.register("ground", () -> new GroundItem());
	public static final RegistryObject<Item> SERVER = block(RanahiromodModBlocks.SERVER);
	public static final RegistryObject<Item> PRIVATE_BOTTLE = REGISTRY.register("private_bottle", () -> new PrivateBottleItem());
	public static final RegistryObject<Item> AIR_CONDITION_BLOCK = block(RanahiromodModBlocks.AIR_CONDITION_BLOCK);
	public static final RegistryObject<Item> WIND_MAGIC_2 = REGISTRY.register("wind_magic_2", () -> new WindMagic2Item());
	public static final RegistryObject<Item> THIS_IS_YOUR_MEAL = REGISTRY.register("this_is_your_meal", () -> new ThisIsYourMealItem());
	public static final RegistryObject<Item> DEVIL_EYE_ARMOR_HELMET = REGISTRY.register("devil_eye_armor_helmet", () -> new DevilEyeArmorItem.Helmet());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
